title: Chadow's Personal Page
author: Chadow

navbar-links:
  About Me: "about_me"

social-network-links:
  rss: true
  github: chadowo
  itchio: chadow

remote_theme: daattali/beautiful-jekyll@6.0.1

