title: Chadow's Personal Page
author: Chadow

plugins:
  - jekyll-remote-theme

navbar-links:
  Home: "index"
  Projects: "projects"
  About Me: "about_me"

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

title-on-all-pages: true

excerpt_length: 50

feed_show_excerpt: true

post_search: true

social-network-links:
  rss: true
  github: chadowo
  itchio: chadow

exclude:
  - LICENSE
  - README.md

giscus:
  hostname: giscus.app 
  repository: chadowo/chadowo.github.io
  repository-id: R_kgDOKRO5MQ 
  category: Announcements
  category-id: DIC_kwDOKRO5Mc4CcOiY
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: light

remote_theme: daattali/beautiful-jekyll@6.0.1

